version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  django:
    build:
      context: ./api/
      dockerfile: ./Dockerfile   
    command: ./django_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django

volumes:
  node-modules:
  db-data:
